### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by berndhopp** [morevaadin/More-Vaadin#11]
The parent POM does include only a single project and I cannot get the spring security example to run, because it does not have the version for vaadin and even when I use the version from the parent pom, it does not compile.

**Comment by nfrankel** [comment]
Hello,
You sure know how to send a request...

**Comment by berndhopp** [comment]
I do and if I had just spotted a runtime exception I may would help you out, but I won't spend my time to fix your BUILD errors. You did not do your due diligence, fix it or delete this crap.

**Comment by berndhopp** [comment]
alright, I excuse for my tone, this was inappropriate and I ask for your excuse. 
The reason I was upset was that moorevaadin.com is quite a popular vaadin resource and for at least about a year now, nobody is able to run any samples from it and everybody who tries will be left with a discouraging experience of unfixable build errors. 
I believe you are able to build this project, however my guess is you either forgot to include some files in git and/or have stuff installed in your .m2 that are not available on the standard mvnrepo. 

best
Bernd
